/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import LectorXML.ConvertirXML;
import LectorXML.LectorXml;
import Pojos.Producto;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author molin
 */
public class IPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public IPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/infopago.png"));
        setIconImage(retValue);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarFactura = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTotalAlimentacion = new javax.swing.JTextField();
        txtTotalVivienda = new javax.swing.JTextField();
        txtTotalEducacion = new javax.swing.JTextField();
        txtTotalSalud = new javax.swing.JTextField();
        txtTotalVestimenta = new javax.swing.JTextField();
        txtTotalOtros = new javax.swing.JTextField();
        txtSubtotalSinIva = new javax.swing.JTextField();
        txtSubtotalIva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRucProvedor = new javax.swing.JTextField();
        lblVivienda = new java.awt.Label();
        lblEducacion = new java.awt.Label();
        lblOtros = new java.awt.Label();
        lblSalud = new java.awt.Label();
        lblVestimenta = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 46, 68));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Gestor de Facturas ");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 0, 126, 24));

        btnBuscarFactura.setBackground(new java.awt.Color(95, 78, 113));
        btnBuscarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search_32px.png"))); // NOI18N
        btnBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacturaActionPerformed(evt);
            }
        });
        panel1.add(btnBuscarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 19, -1, 36));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 520, -1));

        jPanel1.setForeground(new java.awt.Color(89, 199, 198));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 480));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Factura No:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 14, -1, -1));
        jPanel2.add(txtNumFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 11, 126, -1));

        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 14, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 11, 70, -1));

        jLabel5.setText("Ruc:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 48, -1, -1));

        txtRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 45, 126, -1));

        jLabel6.setText("Total Alimentacion:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 182, -1, -1));

        jLabel7.setText("Fecha:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 105, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 102, 126, -1));

        jLabel8.setText("Total Vivienda:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 213, -1, -1));

        jLabel9.setText("Total Educacion:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 244, -1, -1));

        jLabel10.setText("Total Salud:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 275, -1, -1));

        jLabel11.setText("Total Vestimenta:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 306, -1, -1));

        jLabel12.setText("Total Otros:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 337, -1, -1));

        jLabel13.setText("Subtotal sin Iva");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 368, -1, -1));

        jLabel15.setText("Total Factura");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 399, -1, -1));
        jPanel2.add(txtTotalAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 179, 66, -1));
        jPanel2.add(txtTotalVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 210, 66, -1));
        jPanel2.add(txtTotalEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 241, 66, -1));
        jPanel2.add(txtTotalSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 272, 66, -1));
        jPanel2.add(txtTotalVestimenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 303, 65, -1));
        jPanel2.add(txtTotalOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 334, 65, -1));
        jPanel2.add(txtSubtotalSinIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 365, 65, -1));
        jPanel2.add(txtSubtotalIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 396, 65, -1));

        jLabel4.setText("Ruc Prov:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 74, -1, -1));
        jPanel2.add(txtRucProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 71, 126, -1));
        jPanel2.add(lblVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 210, 418, -1));
        jPanel2.add(lblEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 241, 418, -1));
        jPanel2.add(lblOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 334, 418, -1));
        jPanel2.add(lblSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 272, 418, -1));
        jPanel2.add(lblVestimenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 303, 418, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturaActionPerformed
        // TODO add your handling code here:
        //Creamos el objeto JFileChooser
        JFileChooser fc=new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.XML", "xml");
 
        //Le indicamos el filtro
        fc.setFileFilter(filtro);
        String direccion;
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion=fc.showOpenDialog(panel1);
 
        //Si el usuario, pincha en aceptar
        if(seleccion==JFileChooser.APPROVE_OPTION)
        {
 
            //Seleccionamos el fichero
            File fichero=fc.getSelectedFile();
            
            direccion=fichero.getAbsolutePath();
            direccion=direccion.replace("\\", "//");
            
            System.out.println("La direccion:"+direccion);
            //txtDireccion.setText(direccion);
            try(FileReader fr=new FileReader(fichero))
            {
                String cadena="";
                int valor=fr.read();
                while(valor!=-1)
                {
                    cadena=cadena+(char)valor;
                    valor=fr.read();
                }
            } 
            catch (IOException e1) 
            {
                e1.printStackTrace();
            }
            ConvertirXML xmlNuevo;
            try 
            {
                xmlNuevo = new ConvertirXML(direccion);
                LectorXml leerXml = new LectorXml(xmlNuevo.getDireccion());
                leerXml.leerFacturaXml();
                txtNombre.setText(leerXml.getCliente().getNombres());
                txtNumFactura.setText(leerXml.getFactura().getCodigo());
                txtRuc.setText(leerXml.getCliente().getRucCi());
                txtRucProvedor.setText(leerXml.getProveedor().getRuc());
                txtFecha.setText(leerXml.getFactura().getFecha());
                txtSubtotalSinIva.setText(Double.toString(leerXml.getFactura().getTotalSinIva()));
                txtSubtotalIva.setText(Double.toString(leerXml.getFactura().getTotalConIva()));
                txtTotalAlimentacion.setText(Double.toString(leerXml.getFactura().getListaGastos().get(1).getTotalSinIva()));
                txtTotalVestimenta.setText(Double.toString(leerXml.getFactura().getListaGastos().get(0).getTotalSinIva()));
                txtTotalSalud.setText(Double.toString(leerXml.getFactura().getListaGastos().get(2).getTotalSinIva()));
                txtTotalEducacion.setText(Double.toString(leerXml.getFactura().getListaGastos().get(3).getTotalSinIva()));
                txtTotalVivienda.setText(Double.toString(leerXml.getFactura().getListaGastos().get(4).getTotalSinIva()));
                txtTotalOtros.setText(Double.toString(leerXml.getFactura().getListaGastos().get(5).getTotalSinIva()));
                
                for(Producto prod :  leerXml.getFactura().getListaProductos()){
                    if(prod.getTipo().contains("vestimenta")){
                        lblVestimenta.setText(lblVestimenta.getText() + prod.getNombre() + ",");
                    }
                    if(prod.getTipo().contains("vivienda")){
                        lblVivienda.setText(lblVivienda.getText() + prod.getNombre() + ",");
                    }
                    if(prod.getTipo().contains("educacion")){
                        lblEducacion.setText(lblEducacion.getText() + prod.getNombre() + ",");
                    }
                    if(prod.getTipo().contains("salud")){
                        lblSalud.setText(lblSalud.getText() + prod.getNombre() + ",");
                    }
                    if(prod.getTipo().contains("alimentacion")){
                        //lblAlimentacion.setText(lblAlimentacion.getText() + prod.getNombre() + ",");
                    }
                    if(prod.getTipo().contains("otros")){
                        lblOtros.setText(prod.getNombre() + ",");
                    }
                }
                
            } 
            catch (IOException ex) 
            {
                Logger.getLogger(IPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_btnBuscarFacturaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label lblEducacion;
    private java.awt.Label lblOtros;
    private java.awt.Label lblSalud;
    private java.awt.Label lblVestimenta;
    private java.awt.Label lblVivienda;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtRucProvedor;
    private javax.swing.JTextField txtSubtotalIva;
    private javax.swing.JTextField txtSubtotalSinIva;
    private javax.swing.JTextField txtTotalAlimentacion;
    private javax.swing.JTextField txtTotalEducacion;
    private javax.swing.JTextField txtTotalOtros;
    private javax.swing.JTextField txtTotalSalud;
    private javax.swing.JTextField txtTotalVestimenta;
    private javax.swing.JTextField txtTotalVivienda;
    // End of variables declaration//GEN-END:variables
}
