/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import LectorXML.ConvertirXML;
import LectorXML.LectorXml;
import Operaciones.Operaciones;
import Pojos.Gasto;
import Pojos.Producto;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import java.io.*;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author molin
 */
public class PantallaGestor extends javax.swing.JFrame {

    DefaultTableModel modelo;
    DefaultTableModel modeloFacturaNegocio;
    DefaultTableModel modeloGastosNegocio;
    JComboBox comboBoxTipoGasto;
    
    int indexSeleccion;
    int indexSeleccionProductoNegocio;
    ConvertirXML xmlNuevo;
    LectorXml leerXml;
    String direccion;
    String nuevaDireccion;
    String nombreUsuario;
    String direccionProyecto="";
    String direccionBase="src\\ArchivosLecturaAuxiliar\\Bdd.s3db";
    int tipoFacturaIngresar = 1;
    ArrayList<Gasto> listaGastosTemporal = new ArrayList<Gasto>();
    //tipoFacturaIngresar = 1       tipo personal
    //tipoFacturaIngresar = 2       tipo negocio
    //Operaciones operaciones = new Operaciones();
    
    /*
        String direccionBase="src\\ArchivosLecturaAuxiliar";
        direccionBase+="\\\\Bdd.s3db";
     */
    public PantallaGestor() {
        initComponents();
        this.nombreUsuario=System.getProperty("user.name");
        //nuevaDireccion+="\\\\ArchivosGaestorFacturas\\\\BaseDeDatos";
        this.direccionProyecto="C:\\\\Users\\\\"+this.nombreUsuario+"\\\\ArchivosGestorFacturas\\\\BaseDeDatos";
        File carpeta = new File(direccionProyecto);
        carpeta.mkdirs();
        
        this.setLocationRelativeTo(null);
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/infopago.png"));
        setIconImage(retValue);
        setVisible(true);
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre de Producto");
        modelo.addColumn("Tipo de Gasto");
        this.jTableProductos.setModel(modelo);
        
        modeloFacturaNegocio = new DefaultTableModel();
        modeloFacturaNegocio.addColumn("Nombre de Producto");
        modeloFacturaNegocio.addColumn("Tipo de Gasto");
        this.jTableProductosFacturaNegocio.setModel(modeloFacturaNegocio);
        //this.jTableProductosFacturaNegocio.getColumn("Tipo de Gasto").
        /*String[] DATA = { "Dato 1", "Dato 2", "Dato 3", "Dato 4" };
        JComboBox comboBox = new JComboBox(DATA);
        DefaultCellEditor defaultCellEditor=new DefaultCellEditor(comboBox);
        this.jTableProductosFacturaNegocio.getColumnModel().getColumn(1).setCellEditor(defaultCellEditor);*/
        modeloGastosNegocio = new DefaultTableModel();
        modeloGastosNegocio.addColumn("Gasto");
        modeloGastosNegocio.addColumn("Total");
        this.jTableGastosFacturaNegocio.setModel(modeloGastosNegocio);
        
        indexSeleccion = -1;
        indexSeleccionProductoNegocio = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMostrar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImagenPanel = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        lblRegresar = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelFactura = new javax.swing.JPanel();
        lblFactura = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        separador6 = new javax.swing.JSeparator();
        txtCodigoFactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtFecha = new javax.swing.JTextField();
        lblIva = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtIva = new javax.swing.JTextField();
        PanelProveedor = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        separador3 = new javax.swing.JSeparator();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtRucProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtDireccionProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtCiudad = new javax.swing.JTextField();
        panelCliente = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombreCliente = new javax.swing.JTextField();
        txtRuCliente = new javax.swing.JTextField();
        btnIngresarGasto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnRegresarPanel = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        panelOpciones = new javax.swing.JPanel();
        lblFacturaNegocio = new javax.swing.JLabel();
        lblFacturaPersonal = new javax.swing.JLabel();
        panelBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        lblReporte = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalSinIva = new javax.swing.JTextField();
        txtTotalFactura = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        btnAlimentacion = new javax.swing.JButton();
        txtTotalAlimentacion = new javax.swing.JTextField();
        txtTotalVestimenta = new javax.swing.JTextField();
        btnVestimenta = new javax.swing.JButton();
        btnSalud = new javax.swing.JButton();
        txtTotalSalud = new javax.swing.JTextField();
        btnEducacion = new javax.swing.JButton();
        txtTotalEducacion = new javax.swing.JTextField();
        btnVivienda = new javax.swing.JButton();
        txtTotalVivienda = new javax.swing.JTextField();
        btnOtros = new javax.swing.JButton();
        txtTotalOtros = new javax.swing.JTextField();
        panelTablas = new javax.swing.JLayeredPane();
        capaTabla1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        capaTabla2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductosFacturaNegocio = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableGastosFacturaNegocio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 46, 68));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMostrar.setBackground(new java.awt.Color(36, 46, 68));
        PanelMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(89, 199, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shopping Cart_104px.png"))); // NOI18N
        jPanel2.add(lblImagenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel2.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 10));
        jPanel2.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 120, 10));

        btnCerrar.setBackground(new java.awt.Color(89, 199, 198));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back_64px.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        lblRegresar.setBackground(new java.awt.Color(89, 199, 198));
        lblRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(204, 204, 204));
        lblRegresar.setText("Regresar");
        jPanel2.add(lblRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFactura.setBackground(new java.awt.Color(89, 199, 198));
        panelFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFactura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFactura.setForeground(new java.awt.Color(255, 255, 255));
        lblFactura.setText("Datos Factura");
        panelFactura.add(lblFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Codigo:");
        panelFactura.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        panelFactura.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, -1));

        txtCodigoFactura.setBackground(new java.awt.Color(89, 199, 198));
        txtCodigoFactura.setBorder(null);
        panelFactura.add(txtCodigoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha:");
        panelFactura.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        panelFactura.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 10));

        txtFecha.setBackground(new java.awt.Color(89, 199, 198));
        txtFecha.setBorder(null);
        panelFactura.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        lblIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIva.setForeground(new java.awt.Color(255, 255, 255));
        lblIva.setText("IVA:");
        panelFactura.add(lblIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        panelFactura.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, -1));

        txtIva.setBackground(new java.awt.Color(89, 199, 198));
        txtIva.setBorder(null);
        panelFactura.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 20));

        jLayeredPane1.add(panelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 340));
        panelFactura.setVisible(false);

        PanelProveedor.setBackground(new java.awt.Color(89, 199, 198));
        PanelProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProveedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedor.setText("Proveedor");
        PanelProveedor.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        PanelProveedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        PanelProveedor.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, -1));

        txtNombreProveedor.setBackground(new java.awt.Color(89, 199, 198));
        txtNombreProveedor.setBorder(null);
        PanelProveedor.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ruc:");
        PanelProveedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        PanelProveedor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        txtRucProveedor.setBackground(new java.awt.Color(89, 199, 198));
        txtRucProveedor.setBorder(null);
        PanelProveedor.add(txtRucProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion:");
        PanelProveedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        PanelProveedor.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 10));

        txtDireccionProveedor.setBackground(new java.awt.Color(89, 199, 198));
        txtDireccionProveedor.setBorder(null);
        txtDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionProveedorActionPerformed(evt);
            }
        });
        PanelProveedor.add(txtDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ciudad:");
        PanelProveedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        PanelProveedor.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, 180, 10));

        txtCiudad.setBackground(new java.awt.Color(89, 199, 198));
        txtCiudad.setBorder(null);
        PanelProveedor.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 20));

        jLayeredPane1.add(PanelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 320));
        PanelProveedor.setVisible(false);

        panelCliente.setBackground(new java.awt.Color(89, 199, 198));
        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setText("Cliente");
        panelCliente.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombres y Apellidos:");
        panelCliente.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblRuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRuc.setForeground(new java.awt.Color(255, 255, 255));
        lblRuc.setText("Ruc-CI:");
        panelCliente.add(lblRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        panelCliente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));
        panelCliente.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        txtNombreCliente.setBackground(new java.awt.Color(89, 199, 198));
        txtNombreCliente.setBorder(null);
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        panelCliente.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        txtRuCliente.setBackground(new java.awt.Color(89, 199, 198));
        txtRuCliente.setBorder(null);
        panelCliente.add(txtRuCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jLayeredPane1.add(panelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 330));
        panelCliente.setVisible(false);

        jPanel2.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        btnIngresarGasto.setText("Gastos Nuevos");
        btnIngresarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarGastoMouseClicked(evt);
            }
        });
        jPanel2.add(btnIngresarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        PanelMostrar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 590));

        jPanel1.setBackground(new java.awt.Color(12, 15, 22));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCliente.setBackground(new java.awt.Color(12, 15, 22));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Circled User Male_32px.png"))); // NOI18N
        btnCliente.setBorder(null);
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 40, 40));

        btnProveedor.setBackground(new java.awt.Color(12, 15, 22));
        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Move by Trolley_32px.png"))); // NOI18N
        btnProveedor.setBorder(null);
        btnProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedorMouseClicked(evt);
            }
        });
        jPanel1.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 40, -1));

        btnFactura.setBackground(new java.awt.Color(12, 15, 22));
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Purchase Order_32px.png"))); // NOI18N
        btnFactura.setBorder(null);
        btnFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMouseClicked(evt);
            }
        });
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 283, 40, 40));

        btnVolver.setBackground(new java.awt.Color(12, 15, 22));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Forward_32px_1.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 40, 40));

        btnRegresarPanel.setBackground(new java.awt.Color(12, 15, 22));
        btnRegresarPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back_32px.png"))); // NOI18N
        btnRegresarPanel.setBorder(null);
        btnRegresarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPanelMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegresarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 40, -1));
        btnRegresarPanel.setVisible(false);
        btnRegresarPanel.setEnabled(false);

        PanelMostrar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 590));

        btnSalir.setBackground(new java.awt.Color(36, 46, 68));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancel_32px.png"))); // NOI18N
        btnSalir.setText("  Salir  ");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        PanelMostrar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 120, -1));

        btnGuardar.setBackground(new java.awt.Color(36, 46, 68));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(204, 204, 204));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save_32px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        PanelMostrar.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 120, -1));

        btnLimpiar.setBackground(new java.awt.Color(36, 46, 68));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Restart_32px_2.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });
        PanelMostrar.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpciones.setBackground(new java.awt.Color(36, 46, 68));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFacturaNegocio.setFont(new java.awt.Font("Microsoft Tai Le", 0, 28)); // NOI18N
        lblFacturaNegocio.setForeground(new java.awt.Color(255, 255, 255));
        lblFacturaNegocio.setText("Factura de Negocio");
        lblFacturaNegocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacturaNegocioMouseClicked(evt);
            }
        });
        panelOpciones.add(lblFacturaNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        lblFacturaPersonal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFacturaPersonal.setForeground(new java.awt.Color(109, 115, 130));
        lblFacturaPersonal.setText("Factura Personal");
        lblFacturaPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacturaPersonalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFacturaPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFacturaPersonalMouseExited(evt);
            }
        });
        panelOpciones.add(lblFacturaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLayeredPane2.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 60));

        panelBuscar.setBackground(new java.awt.Color(36, 46, 68));
        panelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(36, 46, 68));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search_32px.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBuscar.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        lblBuscar.setBackground(new java.awt.Color(36, 46, 68));
        lblBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar");
        panelBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 50));

        lblReporte.setBackground(new java.awt.Color(36, 46, 68));
        lblReporte.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblReporte.setForeground(new java.awt.Color(109, 115, 130));
        lblReporte.setText("Reporte");
        lblReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReporteMouseExited(evt);
            }
        });
        panelBuscar.add(lblReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 80, 30));

        jLayeredPane2.add(panelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 70));
        panelBuscar.setVisible(false);

        PanelMostrar.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 540, 100));

        jPanel3.setBackground(new java.awt.Color(26, 29, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(109, 115, 130));
        jLabel1.setText("Total sin IVA: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 115, 130));
        jLabel2.setText("Total Factura:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        txtTotalSinIva.setBackground(new java.awt.Color(26, 29, 40));
        txtTotalSinIva.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalSinIva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtTotalSinIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalSinIvaActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalSinIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 20));

        txtTotalFactura.setBackground(new java.awt.Color(26, 29, 40));
        txtTotalFactura.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(txtTotalFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 90, 20));

        PanelMostrar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 570, 40));

        panelBotones.setBackground(new java.awt.Color(36, 46, 68));
        panelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlimentacion.setBackground(new java.awt.Color(107, 116, 147));
        btnAlimentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Restaurant_32px.png"))); // NOI18N
        btnAlimentacion.setEnabled(false);
        btnAlimentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlimentacionMouseClicked(evt);
            }
        });
        btnAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlimentacionActionPerformed(evt);
            }
        });
        panelBotones.add(btnAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtTotalAlimentacion.setBackground(new java.awt.Color(36, 46, 68));
        txtTotalAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalAlimentacion.setText("$ 0.00");
        txtTotalAlimentacion.setBorder(null);
        panelBotones.add(txtTotalAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        txtTotalVestimenta.setBackground(new java.awt.Color(36, 46, 68));
        txtTotalVestimenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalVestimenta.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalVestimenta.setText("$ 0.00");
        txtTotalVestimenta.setBorder(null);
        txtTotalVestimenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVestimentaActionPerformed(evt);
            }
        });
        panelBotones.add(txtTotalVestimenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        btnVestimenta.setBackground(new java.awt.Color(107, 116, 147));
        btnVestimenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clothes_32px.png"))); // NOI18N
        btnVestimenta.setEnabled(false);
        btnVestimenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVestimentaMouseClicked(evt);
            }
        });
        panelBotones.add(btnVestimenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        btnSalud.setBackground(new java.awt.Color(107, 116, 147));
        btnSalud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Doctors Bag_32px.png"))); // NOI18N
        btnSalud.setEnabled(false);
        btnSalud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaludMouseClicked(evt);
            }
        });
        panelBotones.add(btnSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        txtTotalSalud.setBackground(new java.awt.Color(36, 46, 68));
        txtTotalSalud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalSalud.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalSalud.setText("$ 0.00");
        txtTotalSalud.setBorder(null);
        txtTotalSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalSaludActionPerformed(evt);
            }
        });
        panelBotones.add(txtTotalSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btnEducacion.setBackground(new java.awt.Color(107, 116, 147));
        btnEducacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Literature_32px.png"))); // NOI18N
        btnEducacion.setEnabled(false);
        btnEducacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEducacionMouseClicked(evt);
            }
        });
        panelBotones.add(btnEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        txtTotalEducacion.setBackground(new java.awt.Color(36, 46, 68));
        txtTotalEducacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalEducacion.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalEducacion.setText("$ 0.00");
        txtTotalEducacion.setBorder(null);
        panelBotones.add(txtTotalEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        btnVivienda.setBackground(new java.awt.Color(107, 116, 147));
        btnVivienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home_32px.png"))); // NOI18N
        btnVivienda.setEnabled(false);
        btnVivienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViviendaMouseClicked(evt);
            }
        });
        btnVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViviendaActionPerformed(evt);
            }
        });
        panelBotones.add(btnVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        txtTotalVivienda.setBackground(new java.awt.Color(36, 46, 68));
        txtTotalVivienda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalVivienda.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalVivienda.setText("$ 0.00");
        txtTotalVivienda.setBorder(null);
        panelBotones.add(txtTotalVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        btnOtros.setBackground(new java.awt.Color(107, 116, 147));
        btnOtros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ok_32px.png"))); // NOI18N
        btnOtros.setEnabled(false);
        btnOtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOtrosMouseClicked(evt);
            }
        });
        panelBotones.add(btnOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        txtTotalOtros.setBackground(new java.awt.Color(36, 46, 68));
        txtTotalOtros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalOtros.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalOtros.setText("$ 0.00");
        txtTotalOtros.setBorder(null);
        txtTotalOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalOtrosActionPerformed(evt);
            }
        });
        panelBotones.add(txtTotalOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        PanelMostrar.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 540, 90));
        panelBotones.setVisible(false);

        panelTablas.setPreferredSize(new java.awt.Dimension(300, 100));
        panelTablas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capaTabla1.setBackground(new java.awt.Color(36, 46, 68));
        capaTabla1.setPreferredSize(new java.awt.Dimension(280, 230));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 230));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        capaTabla1.add(jScrollPane1);

        panelTablas.add(capaTabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 540, 270));
        capaTabla1.setVisible(false);

        capaTabla2.setBackground(new java.awt.Color(36, 46, 68));
        capaTabla2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 200));
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableProductosFacturaNegocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProductosFacturaNegocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosFacturaNegocioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableProductosFacturaNegocioMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProductosFacturaNegocio);

        capaTabla2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 450, 130));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(452, 200));
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTableGastosFacturaNegocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableGastosFacturaNegocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGastosFacturaNegocioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableGastosFacturaNegocio);

        capaTabla2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 140));

        panelTablas.add(capaTabla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 500));
        capaTabla2.setVisible(false);

        PanelMostrar.add(panelTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 600, 500));

        getContentPane().add(PanelMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        // TODO add your handling code here:
        lblRegresar.setForeground(new Color(204, 204, 204));

    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        // TODO add your handling code here:
        lblRegresar.setForeground(Color.white);
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setForeground(Color.white);
        btnSalir.setBackground(new Color(89, 199, 198));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setForeground(new Color(204,204,204));
        btnSalir.setBackground(new Color(36, 46, 68));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setForeground(Color.white);
        btnGuardar.setBackground(new Color(89, 199, 198));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setForeground(new Color(204,204,204));
        btnGuardar.setBackground(new Color(36, 46, 68));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        // TODO add your handling code here:
        btnLimpiar.setForeground(Color.white);
        btnLimpiar.setBackground(new Color(89, 199, 198));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        // TODO add your handling code here:
        btnLimpiar.setForeground(new Color(204,204,204));
        btnLimpiar.setBackground(new Color(36, 46, 68));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void lblReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteMouseEntered
        // TODO add your handling code here:
        lblReporte.setBackground(new Color(36, 46, 68));
        lblReporte.setForeground(Color.white);
        lblBuscar.setBackground(new Color(36, 46, 68));
        lblBuscar.setForeground(new Color(109, 115, 130));
        
    }//GEN-LAST:event_lblReporteMouseEntered

    private void lblReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteMouseExited
        // TODO add your handling code here:
        lblBuscar.setBackground(new Color(36, 46, 68));
        lblBuscar.setForeground(Color.white);
        lblReporte.setBackground(new Color(36, 46, 68));
        lblReporte.setForeground(new Color(109, 115, 130));
        
    }//GEN-LAST:event_lblReporteMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViviendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViviendaActionPerformed

    private void txtTotalSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalSaludActionPerformed

    private void txtTotalOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalOtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalOtrosActionPerformed

    private void txtTotalVestimentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVestimentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalVestimentaActionPerformed

    private void btnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseClicked
        // TODO add your handling code here:
        lblImagenPanel.setVisible(false);
        separador1.setVisible(false);
        separador2.setVisible(false);
        panelCliente.setVisible(true);
        PanelProveedor.setVisible(false);
        panelFactura.setVisible(false);
        
    }//GEN-LAST:event_btnClienteMouseClicked

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        lblImagenPanel.setVisible(true);
        separador1.setVisible(true);
        separador2.setVisible(true);
        panelCliente.setVisible(false);
        PanelProveedor.setVisible(false);
        panelFactura.setVisible(false);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void txtDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionProveedorActionPerformed

    private void btnProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorMouseClicked
        // TODO add your handling code here:
        lblImagenPanel.setVisible(false);
        separador1.setVisible(false);
        separador2.setVisible(false);
        PanelProveedor.setVisible(true);
        panelFactura.setVisible(false);
        panelCliente.setVisible(false);
        
    }//GEN-LAST:event_btnProveedorMouseClicked

    private void btnFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseClicked
        // TODO add your handling code here:
        lblImagenPanel.setVisible(false);
        separador1.setVisible(false);
        separador2.setVisible(false);
        panelFactura.setVisible(true);
        panelCliente.setVisible(false);
        PanelProveedor.setVisible(false);
    }//GEN-LAST:event_btnFacturaMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        
        this.borrarGUI();
        
        JFileChooser fc=new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.XML", "xml");
        //Le indicamos el filtro
        fc.setFileFilter(filtro);
        //String direccion;
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion=fc.showOpenDialog(PanelMostrar);        
        //tipoFacturaIngresar = 1       tipo personal
        //tipoFacturaIngresar = 2       tipo negocio
 
        //Si el usuario, pincha en aceptar
        if(seleccion==JFileChooser.APPROVE_OPTION)
        {
            //Seleccionamos el fichero
            File fichero=fc.getSelectedFile();   
            direccion=fichero.getAbsolutePath();
            direccion=direccion.replace("\\", "//");
            try(FileReader fr=new FileReader(fichero))
            {
                String cadena="";
                int valor=fr.read();
                while(valor!=-1)
                {
                    cadena=cadena+(char)valor;
                    valor=fr.read();
                }
            } 
            catch (IOException e1) 
            {
                e1.printStackTrace();
            }
            //ConvertirXML xmlNuevo;
            try 
            {
                this.xmlNuevo = new ConvertirXML(direccion);
                this.leerXml = new LectorXml(xmlNuevo.getDireccion());
                //tipoFacturaIngresar = 1       tipo personal
                //tipoFacturaIngresar = 2       tipo negocio
                leerXml.leerFacturaXml(this.tipoFacturaIngresar);
                //comprobar si existe la factura
                Operaciones operaciones = new Operaciones(this.direccionBase);
                operaciones.conectar();
                
                if((operaciones.existeFactura(leerXml.getFactura().getCodigo(),
                        leerXml.getCliente().getRucCi(),
                        leerXml.getProveedor().getRuc())) &&
                        (operaciones.existeFacturaNegocio(leerXml.getFactura().getCodigo(),
                        leerXml.getCliente().getRucCi(),
                        leerXml.getProveedor().getRuc()))){ 
                    //leerGastosGuardados y proveedor nuevo
                    String entrada[] = new String[2];
                    if(tipoFacturaIngresar == 2){
                        //nuevo proveedor, ingreso de tipo de gasto
                        if(operaciones.existeProveedor(leerXml.getProveedor().getRuc())){
                            String gastoProveedorNuevo = JOptionPane.showInputDialog(null, 
                                    "Ingrese el tipo de gasto de : " + leerXml.getProveedor().getNombre(),
                                    "Proveedor Nuevo", JOptionPane.QUESTION_MESSAGE);
                            leerXml.getProveedor().setTipoGasto(gastoProveedorNuevo);
                            //this.listaGastosTemporal.add(new Gasto((gastoProveedorNuevo)));
                            this.leerXml.getFacturaNegocio().getListaGastos().add(new Gasto((gastoProveedorNuevo)));
                            //this.leerXml.getFacturaNegocio().actualizarValores();
                            this.listaGastosTemporal.add(this.leerXml.getFacturaNegocio().getListaGastos().get(0));
                        }
                        for(Producto prod :  leerXml.getFacturaNegocio().getListaProductos()){
                            //JOptionPane.showMessageDialog(null, prod);
                            entrada[0] = prod.getNombre();
                            if(operaciones.existeProductoTipoDeGasto(prod.getNombre()) == null){
                                //JOptionPane.showMessageDialog(null, "ingresa tipo de gasto de proveedor");
                                prod.setTipo(leerXml.getProveedor().getTipoGasto());
                            }
                            else{
                                prod.setTipo(operaciones.existeProductoTipoDeGasto(prod.getNombre()));
                            }
                            entrada[1] = prod.getTipo();
                            modeloFacturaNegocio.addRow(entrada);
                        }
                        this.leerXml.getFacturaNegocio().actualizarValores();
                        leerGastosDeNegocioGuardados();
                        this.llenarComboBoxGastos();
                    }else{
                        String gastoProveedorNuevo = "";
                        if(operaciones.existeProveedor(leerXml.getProveedor().getRuc())){
                            int opcionTipoProveedor = JOptionPane.showOptionDialog(
                            null, "Seleccione el tipo de gasto", "Nuevo Proveedor", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, 
                            new Object[] {"Vestimenta", "Alimentacion", "Salud", "Educacion", "Vivienda"}, "Vestimenta");
                            if(opcionTipoProveedor == 0) gastoProveedorNuevo = "vestimenta";
                            if(opcionTipoProveedor == 1) gastoProveedorNuevo = "alimentacion";
                            if(opcionTipoProveedor == 2) gastoProveedorNuevo = "salud";
                            if(opcionTipoProveedor == 3) gastoProveedorNuevo = "educacion";
                            if(opcionTipoProveedor == 4) gastoProveedorNuevo = "vivienda";
                        }
                        leerXml.getProveedor().setTipoGasto(gastoProveedorNuevo);
                    }
                    //JOptionPane.showMessageDialog(null, leerXml.getProveedor());
                    //cargar datos proveedor
                    txtNombreProveedor.setText(leerXml.getProveedor().getNombre());
                    txtRucProveedor.setText(leerXml.getProveedor().getRuc());
                    txtDireccionProveedor.setText(leerXml.getProveedor().getDireccion());
                    //cargar datos cliente
                    txtNombreCliente.setText(leerXml.getCliente().getNombres());
                    txtRuCliente.setText(leerXml.getCliente().getRucCi());

                    txtCodigoFactura.setText(leerXml.getFactura().getCodigo());
                    txtFecha.setText(leerXml.getFactura().getFecha());
                    txtTotalSinIva.setText(Double.toString(leerXml.getFactura().getTotalSinIva()));
                    txtTotalFactura.setText(Double.toString(leerXml.getFactura().getTotalConIva()));
                    txtIva.setText(Double.toString(leerXml.getFactura().getIva()));
                    this.ingresarValoresGastos();
                    //JOptionPane.showMessageDialog(null, leerXml.getFactura().getListaProductos().size());
                    
                    if(tipoFacturaIngresar == 1){
                        for(Producto prod :  leerXml.getFactura().getListaProductos()){
                            //JOptionPane.showMessageDialog(null, prod);
                            entrada[0] = prod.getNombre();
                            entrada[1] = prod.getTipo();
                            modelo.addRow(entrada);
                        }
                    }
                    
                    this.desbloquearBotonesGastos();
                }
                else{
                    JOptionPane.showMessageDialog(null, "LA FACTURA YA HA SIDO INGRESADA ANTERIORMENTE");
                }
            } 
            catch (IOException ex) 
            {
                Logger.getLogger(IPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    public void ingresarValoresGastos(){
        DecimalFormat df = new DecimalFormat("#.##");
        txtTotalAlimentacion.setText(df.format(leerXml.getFactura().getListaGastos().get(1).getTotalSinIva()));
        //txtTotalAlimentacion.setText(Double.toString(leerXml.getFactura().getListaGastos().get(1).getTotalSinIva()));
        txtTotalVestimenta.setText(df.format(leerXml.getFactura().getListaGastos().get(0).getTotalSinIva()));
        txtTotalSalud.setText(df.format(leerXml.getFactura().getListaGastos().get(2).getTotalSinIva()));
        txtTotalEducacion.setText(df.format(leerXml.getFactura().getListaGastos().get(3).getTotalSinIva()));
        txtTotalVivienda.setText(df.format(leerXml.getFactura().getListaGastos().get(4).getTotalSinIva()));
        txtTotalOtros.setText(df.format(leerXml.getFactura().getListaGastos().get(5).getTotalSinIva()));
    }
    
    public void llenarComboBoxGastos(){
        //String[] DATA = { "Dato 1", "Dato 2", "Dato 3", "Dato 4"};
        String[] DATA = new String[this.listaGastosTemporal.size()];
        String[] entrada = new String[2];
        //int val = 0;
        int i = 0;
        for(Gasto gasto : this.listaGastosTemporal){
            entrada[0] = gasto.getTipo();
            //entrada[1] = String.valueOf(val);
            entrada[1] = String.valueOf(gasto.getTotalSinIva());
            modeloGastosNegocio.addRow(entrada);
            DATA[i] = gasto.getTipo();
            i++;
        }
        comboBoxTipoGasto = new JComboBox(DATA);
        
        DefaultCellEditor defaultCellEditor=new DefaultCellEditor(comboBoxTipoGasto);
        this.jTableProductosFacturaNegocio.getColumnModel().getColumn(1).setCellEditor(defaultCellEditor);
        this.comboBoxTipoGasto.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                int seleccion = jTableProductosFacturaNegocio.getEditingRow();
                if(seleccion != -1){
                    //JOptionPane.showMessageDialog(null, "Fila en edicion "+seleccion);
                    //JOptionPane.showMessageDialog(null, "Fila "+seleccion+
                            //"columna "+ 1 + comboBoxTipoGasto.getSelectedItem());
                    cambioTipoGastoProductoFacturaNegocio(seleccion, comboBoxTipoGasto.getSelectedItem().toString());
                }
                //JOptionPane.showMessageDialog(null, "Fila en edicion "+jTableProductosFacturaNegocio.getEditingRow());
                //JOptionPane.showMessageDialog(null, "Fila getSelectedRow "+jTableProductosFacturaNegocio.getSelectedRow());
            }
        });
    }
    
    public void leerGastosDeNegocioGuardados(){
        Operaciones operaciones = new Operaciones(this.direccionBase);
        operaciones.conectar();
        for(String nombreGasto : operaciones.leerNombreDeGastosDeNegocioGuardadados()){
            //JOptionPane.showMessageDialog(null, nombreGasto);
            //this.comboGastosNegocio.addItem(nombreGasto);
            this.listaGastosTemporal.add(new Gasto(nombreGasto));
            this.leerXml.getFacturaNegocio().setGasto(new Gasto(nombreGasto));
        }
        
    }
    
    public void cambioTipoGastoProductoFacturaNegocio(int seleccionTablaProductos, String tipoGastoNegocio){
        this.leerXml.getFacturaNegocio().getListaProductos().get(seleccionTablaProductos).setTipo(tipoGastoNegocio);
        this.leerXml.getFacturaNegocio().actualizarValores();
        while(modeloGastosNegocio.getRowCount()>0)modeloGastosNegocio.removeRow(0);
        String[] entrada = new String[2];
        //int val = 0;
        for(Gasto gasto : this.leerXml.getFacturaNegocio().getListaGastos()){
            entrada[0] = gasto.getTipo();
            entrada[1] = String.valueOf(gasto.getTotalSinIva());
            modeloGastosNegocio.addRow(entrada);
        }
        /*Gasto gastoSumar;
        int i = 0;
        for(Gasto gasto : this.leerXml.getFacturaNegocio().getListaGastos()){
            if(gasto.getTipo().compareToIgnoreCase(tipoGastoNegocio) == 0){
                modeloGastosNegocio.setValueAt(gasto.getTotalSinIva(), i, 1);
            }
            else{
                i++;
            }
        }*/
    }
    
    /*public void ingresarValoresGastosFacturaNegocioEnModelo(){
        modeloGastosNegocio.setValueAt("alimentacion", this.indexSeleccion, 1);
        
    }*/
    
    /*public void ingresarValoresGastos(){
        DecimalFormat df = new DecimalFormat("#.##");
        txtTotalAlimentacion.setText(df.format(leerXml.getFactura().getListaGastos().get(1).getTotalSinIva()));
        //txtTotalAlimentacion.setText(Double.toString(leerXml.getFactura().getListaGastos().get(1).getTotalSinIva()));
        txtTotalVestimenta.setText(df.format(leerXml.getFactura().getListaGastos().get(0).getTotalSinIva()));
        txtTotalSalud.setText(df.format(leerXml.getFactura().getListaGastos().get(2).getTotalSinIva()));
        txtTotalEducacion.setText(df.format(leerXml.getFactura().getListaGastos().get(3).getTotalSinIva()));
        txtTotalVivienda.setText(df.format(leerXml.getFactura().getListaGastos().get(4).getTotalSinIva()));
        txtTotalOtros.setText(df.format(leerXml.getFactura().getListaGastos().get(5).getTotalSinIva()));
    }*/
    
    private void btnAlimentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlimentacionMouseClicked
        // TODO add your handling code here:
        modelo.setValueAt("alimentacion", this.indexSeleccion, 1);
        this.leerXml.getFactura().getListaProductos().get(this.indexSeleccion).setTipo("alimentacion");
        this.leerXml.getFactura().actualizarValores();
        this.ingresarValoresGastos();
    }//GEN-LAST:event_btnAlimentacionMouseClicked

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        // TODO add your handling code here:
        this.indexSeleccion = this.jTableProductos.getSelectedRow();
        //JOptionPane.showMessageDialog(null, this.indexSeleccion);
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void btnVestimentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVestimentaMouseClicked
        // TODO add your handling code here:
        modelo.setValueAt("vestimenta", this.indexSeleccion, 1);
        this.leerXml.getFactura().getListaProductos().get(this.indexSeleccion).setTipo("vestimenta");
        this.leerXml.getFactura().actualizarValores();
        this.ingresarValoresGastos();
    }//GEN-LAST:event_btnVestimentaMouseClicked

    private void btnSaludMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaludMouseClicked
        // TODO add your handling code here:
        modelo.setValueAt("salud", this.indexSeleccion, 1);
        this.leerXml.getFactura().getListaProductos().get(this.indexSeleccion).setTipo("salud");
        this.leerXml.getFactura().actualizarValores();
        this.ingresarValoresGastos();
    }//GEN-LAST:event_btnSaludMouseClicked

    private void btnEducacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEducacionMouseClicked
        // TODO add your handling code here:
        modelo.setValueAt("educacion", this.indexSeleccion, 1);
        this.leerXml.getFactura().getListaProductos().get(this.indexSeleccion).setTipo("educacion");
        this.leerXml.getFactura().actualizarValores();
        this.ingresarValoresGastos();
    }//GEN-LAST:event_btnEducacionMouseClicked

    private void btnViviendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViviendaMouseClicked
        // TODO add your handling code here:
        modelo.setValueAt("vivienda", this.indexSeleccion, 1);
        this.leerXml.getFactura().getListaProductos().get(this.indexSeleccion).setTipo("vivienda");
        this.leerXml.getFactura().actualizarValores();
        this.ingresarValoresGastos();
    }//GEN-LAST:event_btnViviendaMouseClicked

    private void btnOtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtrosMouseClicked
        // TODO add your handling code here:
        modelo.setValueAt("otros", this.indexSeleccion, 1);
        this.leerXml.getFactura().getListaProductos().get(this.indexSeleccion).setTipo("otros");
        this.leerXml.getFactura().actualizarValores();
        this.ingresarValoresGastos();
    }//GEN-LAST:event_btnOtrosMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        
        System.out.println("Dir base:"+direccionBase);
        
        Operaciones operaciones = new Operaciones(this.direccionBase);
        operaciones.conectar();
        //JOptionPane.showMessageDialog(null, "guardando cliente....");
        operaciones.guardarCliente(this.leerXml.getCliente(), this.leerXml.getFactura().getFecha());
        //JOptionPane.showMessageDialog(null, "guardando proveedor....");
        operaciones.guardarProveedor(this.leerXml.getProveedor());
        //JOptionPane.showMessageDialog(null, "guardando factura....");
        operaciones.guardarFactura(this.leerXml.getFactura());
        
        JOptionPane.showMessageDialog(null, "....Factura ingresada exitosamente");
        //while(modelo.getRowCount()>0)modelo.removeRow(0);
        
        //txtTotalSinIva.setText("");
        //txtTotalFactura.setText("");
        this.borrarGUI();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void lblReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteMouseClicked
        // TODO add your handling code here:
        //String direccionBase=this.direccionProyecto+"\\\\Bdd.s3db";
        String direccionBase="src\\ArchivosLecturaAuxiliar";
        direccionBase+="\\\\Bdd.s3db";
        Reportes reporte = new Reportes(direccionBase);
        this.dispose();
        reporte.setVisible(true);
    }//GEN-LAST:event_lblReporteMouseClicked

    private void txtTotalSinIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSinIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalSinIvaActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        //while(modelo.getRowCount()>0)modelo.removeRow(0);
        //txtTotalSinIva.setText("");
        //txtTotalFactura.setText("");
        this.borrarGUI();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void lblFacturaPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturaPersonalMouseEntered
        // TODO add your handling code here:
        lblFacturaPersonal.setBackground(new Color(36, 46, 68));
        lblFacturaPersonal.setForeground(Color.white);
        lblFacturaNegocio.setBackground(new Color(36, 46, 68));
        lblFacturaNegocio.setForeground(new Color(109, 115, 130));
    }//GEN-LAST:event_lblFacturaPersonalMouseEntered

    private void lblFacturaPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturaPersonalMouseExited
        // TODO add your handling code here:
        lblFacturaNegocio.setBackground(new Color(36, 46, 68));
        lblFacturaNegocio.setForeground(Color.white);
        lblFacturaPersonal.setBackground(new Color(36, 46, 68));
        lblFacturaPersonal.setForeground(new Color(109, 115, 130));
    }//GEN-LAST:event_lblFacturaPersonalMouseExited

    private void lblFacturaNegocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturaNegocioMouseClicked
        // TODO add your handling code here:
        //tipoFacturaIngresar = 1       tipo personal
        //tipoFacturaIngresar = 2       tipo negocio
        this.tipoFacturaIngresar = 2;
        panelOpciones.setVisible(false);
        panelBuscar.setVisible(true);
        //lblGastoNegocio.setVisible(true);
        //comboGastosNegocio.setVisible(true);
        btnRegresarPanel.setVisible(true);
        btnRegresarPanel.setEnabled(true);
        capaTabla2.setVisible(true);
    }//GEN-LAST:event_lblFacturaNegocioMouseClicked

    private void lblFacturaPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturaPersonalMouseClicked
        // TODO add your handling code here:
        //tipoFacturaIngresar = 1       tipo personal
        //tipoFacturaIngresar = 2       tipo negocio
        this.tipoFacturaIngresar = 1;
        panelOpciones.setVisible(false);
        panelBuscar.setVisible(true);
        //lblGastoNegocio.setVisible(false);
        //comboGastosNegocio.setVisible(false);
        btnRegresarPanel.setVisible(true);
        btnRegresarPanel.setEnabled(true);
        capaTabla1.setVisible(true);
        panelBotones.setVisible(true);
    }//GEN-LAST:event_lblFacturaPersonalMouseClicked

    private void btnRegresarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPanelMouseClicked
        // TODO add your handling code here:
        btnRegresarPanel.setVisible(false);
        btnRegresarPanel.setEnabled(false);
        panelOpciones.setVisible(true);
        panelBuscar.setVisible(false);
        panelBotones.setVisible(false);
        capaTabla1.setVisible(false);
        capaTabla2.setVisible(false);
        //lblGastoNegocio.setVisible(false);
        //comboGastosNegocio.setVisible(false);
    }//GEN-LAST:event_btnRegresarPanelMouseClicked

    private void btnIngresarGastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarGastoMouseClicked
        // TODO add your handling code here:
        String nombreNuevoGasto = JOptionPane.showInputDialog("Ingrese nuevo gasto");
        //this.listaGastosTemporal.add(e)
        Gasto gastoNuevo = new Gasto(nombreNuevoGasto);
        this.listaGastosTemporal.add(gastoNuevo);
        //this.comboGastosNegocio.addItem(gastoNuevo.getTipo());
        this.llenarComboBoxGastos();
    }//GEN-LAST:event_btnIngresarGastoMouseClicked

    private void jTableProductosFacturaNegocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosFacturaNegocioMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, this.jTableProductosFacturaNegocio.getSelectedRow());
        //this.indexSeleccionProductoNegocio = this.jTableProductosFacturaNegocio.getSelectedRow();
        //this.indexSeleccion = this.jTableProductos.getSelectedRow();
    }//GEN-LAST:event_jTableProductosFacturaNegocioMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTableGastosFacturaNegocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGastosFacturaNegocioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableGastosFacturaNegocioMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void jTableProductosFacturaNegocioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosFacturaNegocioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProductosFacturaNegocioMouseEntered

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlimentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlimentacionActionPerformed

    public String direccionAbsoluta(String dir)
    {
        String auxiliar="";
        int i=0, contador=0;
                
        do
        {
            if(dir.substring(i, i+1).equals("\\")||dir.substring(i, i+1).equals("/"))
            {
                contador++;
            }
            auxiliar+=dir.substring(i, i+1);
            i++;
        }
        while(i<dir.length()-1&&contador<=4);
        return auxiliar;
    }
    
    public void borrarGUI(){
        while(modelo.getRowCount()>0)modelo.removeRow(0);
        
        txtTotalSinIva.setText("");
        txtTotalFactura.setText("");
        txtCodigoFactura.setText("");
        txtFecha.setText("");
        txtIva.setText("");
        txtNombreProveedor.setText("");
        txtRucProveedor.setText("");
        txtDireccionProveedor.setText("");
        txtCiudad.setText("");
        txtNombreCliente.setText("");
        txtRuCliente.setText("");
        txtTotalAlimentacion.setText("");
        txtTotalEducacion.setText("");
        txtTotalSalud.setText("");
        txtTotalVivienda.setText("");
        txtTotalVestimenta.setText("");
        txtTotalOtros.setText("");
    }
    
    public void desbloquearBotonesGastos(){
        btnAlimentacion.setEnabled(true);
        btnEducacion.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnVestimenta.setEnabled(true);
        btnSalud.setEnabled(true);
        btnVivienda.setEnabled(true);
        btnOtros.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMostrar;
    private javax.swing.JPanel PanelProveedor;
    private javax.swing.JButton btnAlimentacion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEducacion;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresarGasto;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOtros;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnRegresarPanel;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalud;
    private javax.swing.JButton btnVestimenta;
    private javax.swing.JButton btnVivienda;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel capaTabla1;
    private javax.swing.JPanel capaTabla2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTableGastosFacturaNegocio;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTable jTableProductosFacturaNegocio;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblFacturaNegocio;
    private javax.swing.JLabel lblFacturaPersonal;
    private javax.swing.JLabel lblImagenPanel;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelFactura;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JLayeredPane panelTablas;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador6;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoFactura;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtRuCliente;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtTotalAlimentacion;
    private javax.swing.JTextField txtTotalEducacion;
    private javax.swing.JTextField txtTotalFactura;
    private javax.swing.JTextField txtTotalOtros;
    private javax.swing.JTextField txtTotalSalud;
    private javax.swing.JTextField txtTotalSinIva;
    private javax.swing.JTextField txtTotalVestimenta;
    private javax.swing.JTextField txtTotalVivienda;
    // End of variables declaration//GEN-END:variables
}
