/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import GeneradorExcel.Exporter;
import GeneradorPDF.ExporterPDF;
import Operaciones.Operaciones;
import Pojos.Cliente;
import Pojos.Proveedor;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author molin
 */
public class PresentarFactura extends javax.swing.JFrame {

    /**
     * Creates new form PresentarFactura
     */
    private int x, y;
    String strCliente, strProveedor, strAnio;
    JTable tabla;
    Object []fila;
    String direccionBase;
    DecimalFormat formateador = new DecimalFormat("###.##");

    public PresentarFactura(String cliente, Object []row) {
        initComponents();
        this.setLocationRelativeTo(null);
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/infopago.png"));
        setIconImage(retValue);
        this.strCliente=cliente;
        this.fila=row;
        setVisible(true);
        direccionBase="src\\ArchivosLecturaAuxiliar";
        direccionBase+="\\\\Bdd.s3db";
        double totalSinIva, total, iva;
        
        panelFactura.setVisible(false);
        Operaciones operaciones = new Operaciones(this.direccionBase);
        operaciones.conectar();
        Proveedor aux = operaciones.consultarProveedor((String) fila[0]);
        Cliente auxCliente = operaciones.consultarCliente(strCliente);
        txtCedula.setText(auxCliente.getRucCi());
        txtRuc.setText(aux.getRuc());
        txtDireccion.setText(aux.getDireccion());
        txtNumeroFactura.setText((String) fila[1]);
        txtFecha.setText((String)fila[2]);
        txtProveedor.setText((String) fila[0]);
        txtTotalFactura.setText(formateador.format(fila[4]));
        txtIva.setText(formateador.format(fila[3]));
        
        total=Double.parseDouble(fila[4].toString());
        
        iva=Double.parseDouble(fila[3].toString());
        totalSinIva=total-iva;       
        txtTotalSinIva.setText(Double.toString(totalSinIva));
        
        txtNombreCliente.setText(strCliente);
        lblVestimenta.setText(formateador.format(fila[5]));
        lblAlimentacion.setText(formateador.format(fila[6]));
        lblSalud.setText(formateador.format(fila[7]));
        lblEducacion.setText(formateador.format(fila[8]));
        lblVivienda.setText(formateador.format(fila[9]));
        lblOtros.setText(formateador.format(fila[10]));
        try {
            operaciones.consultarProductos((DefaultTableModel)jTable1.getModel(), (String) fila[1]);
            
        } catch (SQLException ex) {
            //Logger.getLogger(PresentarFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private PresentarFactura() {
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtNumeroFactura1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        txtProveedor1 = new javax.swing.JTextField();
        txtRuc1 = new javax.swing.JTextField();
        txtCiudad1 = new javax.swing.JTextField();
        txtDireccion1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        txtNombreCliente1 = new javax.swing.JTextField();
        txtCedula1 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTotalSinIva1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIva1 = new javax.swing.JTextField();
        txtTotalFactura1 = new javax.swing.JTextField();
        btnExportarExcel1 = new javax.swing.JButton();
        btnExportarPDF1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        lblOtros1 = new javax.swing.JLabel();
        lblAlimentacion1 = new javax.swing.JLabel();
        lblVestimenta1 = new javax.swing.JLabel();
        lblSalud1 = new javax.swing.JLabel();
        lblEducacion1 = new javax.swing.JLabel();
        lblVivienda1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        panelFactura1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaFactura1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtProveedor = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtNombreCliente = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalSinIva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        txtTotalFactura = new javax.swing.JTextField();
        btnExportarExcel = new javax.swing.JButton();
        btnExportarPDF = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblOtros = new javax.swing.JLabel();
        lblAlimentacion = new javax.swing.JLabel();
        lblVestimenta = new javax.swing.JLabel();
        lblSalud = new javax.swing.JLabel();
        lblEducacion = new javax.swing.JLabel();
        lblVivienda = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        panelFactura = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setUndecorated(true);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(36, 46, 68));
        jPanel7.setMaximumSize(new java.awt.Dimension(850, 820));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel7MouseReleased(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(12, 15, 22));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(12, 15, 22));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back_64px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 60));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 820));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Visor Facturas");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel9.setBackground(new java.awt.Color(109, 115, 130));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("No:");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNumeroFactura1.setBackground(new java.awt.Color(109, 115, 130));
        txtNumeroFactura1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumeroFactura1.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroFactura1.setBorder(null);
        jPanel9.add(txtNumeroFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fecha:");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtFecha1.setBackground(new java.awt.Color(109, 115, 130));
        txtFecha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFecha1.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha1.setBorder(null);
        jPanel9.add(txtFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 230, 20));
        jPanel9.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 220, -1));
        jPanel9.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 220, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 310, 80));

        jPanel10.setBackground(new java.awt.Color(109, 115, 130));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Move by Trolley_52px.png"))); // NOI18N
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Proveedor:");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ruc: ");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Ciudad:");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Direccion:");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
        jPanel10.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 470, 10));
        jPanel10.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 190, -1));
        jPanel10.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 220, -1));
        jPanel10.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 470, -1));

        txtProveedor1.setBackground(new java.awt.Color(109, 115, 130));
        txtProveedor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProveedor1.setForeground(new java.awt.Color(255, 255, 255));
        txtProveedor1.setToolTipText("");
        txtProveedor1.setBorder(null);
        txtProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedor1ActionPerformed(evt);
            }
        });
        jPanel10.add(txtProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 470, 20));

        txtRuc1.setBackground(new java.awt.Color(109, 115, 130));
        txtRuc1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRuc1.setForeground(new java.awt.Color(255, 255, 255));
        txtRuc1.setBorder(null);
        jPanel10.add(txtRuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, 20));

        txtCiudad1.setBackground(new java.awt.Color(109, 115, 130));
        txtCiudad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCiudad1.setForeground(new java.awt.Color(255, 255, 255));
        txtCiudad1.setBorder(null);
        jPanel10.add(txtCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 220, 20));

        txtDireccion1.setBackground(new java.awt.Color(109, 115, 130));
        txtDireccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion1.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion1.setBorder(null);
        jPanel10.add(txtDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 470, 20));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 730, 110));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 730, 130));

        jPanel11.setBackground(new java.awt.Color(109, 115, 130));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gender Neutral User_52px_4.png"))); // NOI18N
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Nombre:");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Ruc-CI:");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));
        jPanel11.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 470, -1));
        jPanel11.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 470, 10));

        txtNombreCliente1.setBackground(new java.awt.Color(109, 115, 130));
        txtNombreCliente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreCliente1.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente1.setBorder(null);
        jPanel11.add(txtNombreCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 470, 20));

        txtCedula1.setBackground(new java.awt.Color(109, 115, 130));
        txtCedula1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCedula1.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula1.setBorder(null);
        jPanel11.add(txtCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 470, 20));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 730, 80));

        jPanel12.setBackground(new java.awt.Color(26, 29, 40));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(109, 115, 130));
        jLabel6.setText("Total sin IVA: ");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(109, 115, 130));
        jLabel7.setText("Total Factura:");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        txtTotalSinIva1.setBackground(new java.awt.Color(26, 29, 40));
        txtTotalSinIva1.setForeground(new java.awt.Color(109, 115, 130));
        txtTotalSinIva1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel12.add(txtTotalSinIva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, 20));

        jLabel8.setBackground(new java.awt.Color(109, 115, 130));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(109, 115, 130));
        jLabel8.setText("IVA:");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        txtIva1.setBackground(new java.awt.Color(26, 29, 40));
        txtIva1.setForeground(new java.awt.Color(109, 115, 130));
        txtIva1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel12.add(txtIva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 80, 20));

        txtTotalFactura1.setBackground(new java.awt.Color(26, 29, 40));
        txtTotalFactura1.setForeground(new java.awt.Color(109, 115, 130));
        txtTotalFactura1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel12.add(txtTotalFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, -1));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 800, 40));

        btnExportarExcel1.setBackground(new java.awt.Color(36, 46, 68));
        btnExportarExcel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExportarExcel1.setForeground(new java.awt.Color(204, 204, 204));
        btnExportarExcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Microsoft Excel_32px_4.png"))); // NOI18N
        btnExportarExcel1.setText("Exportar");
        btnExportarExcel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportarExcel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportarExcel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportarExcel1MouseExited(evt);
            }
        });
        jPanel7.add(btnExportarExcel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 130, 40));

        btnExportarPDF1.setBackground(new java.awt.Color(36, 46, 68));
        btnExportarPDF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExportarPDF1.setForeground(new java.awt.Color(204, 204, 204));
        btnExportarPDF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PDF 2_32px.png"))); // NOI18N
        btnExportarPDF1.setText("Exportar");
        btnExportarPDF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportarPDF1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportarPDF1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportarPDF1MouseExited(evt);
            }
        });
        btnExportarPDF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDF1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnExportarPDF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, -1, -1));

        btnSalir1.setBackground(new java.awt.Color(36, 46, 68));
        btnSalir1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancel_32px.png"))); // NOI18N
        btnSalir1.setText(" Salir");
        btnSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalir1MouseExited(evt);
            }
        });
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 120, -1));

        lblOtros1.setBackground(new java.awt.Color(36, 46, 68));
        lblOtros1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOtros1.setForeground(new java.awt.Color(255, 255, 255));
        lblOtros1.setText("$ 0.00");
        jPanel7.add(lblOtros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, -1, -1));

        lblAlimentacion1.setBackground(new java.awt.Color(36, 46, 68));
        lblAlimentacion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAlimentacion1.setForeground(new java.awt.Color(255, 255, 255));
        lblAlimentacion1.setText("$ 0.00");
        jPanel7.add(lblAlimentacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, -1));

        lblVestimenta1.setBackground(new java.awt.Color(36, 46, 68));
        lblVestimenta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVestimenta1.setForeground(new java.awt.Color(255, 255, 255));
        lblVestimenta1.setText("$ 0.00");
        jPanel7.add(lblVestimenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        lblSalud1.setBackground(new java.awt.Color(36, 46, 68));
        lblSalud1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSalud1.setForeground(new java.awt.Color(255, 255, 255));
        lblSalud1.setText("$ 0.00");
        jPanel7.add(lblSalud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        lblEducacion1.setBackground(new java.awt.Color(36, 46, 68));
        lblEducacion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEducacion1.setForeground(new java.awt.Color(255, 255, 255));
        lblEducacion1.setText("$ 0.00");
        jPanel7.add(lblEducacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));

        lblVivienda1.setBackground(new java.awt.Color(36, 46, 68));
        lblVivienda1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVivienda1.setForeground(new java.awt.Color(255, 255, 255));
        lblVivienda1.setText("$ 0.00");
        jPanel7.add(lblVivienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, -1));

        jButton11.setBackground(new java.awt.Color(107, 116, 147));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Restaurant_32px.png"))); // NOI18N
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jButton12.setBackground(new java.awt.Color(107, 116, 147));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clothes_32px.png"))); // NOI18N
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jButton13.setBackground(new java.awt.Color(107, 116, 147));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Literature_32px.png"))); // NOI18N
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        jButton14.setBackground(new java.awt.Color(107, 116, 147));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home_32px.png"))); // NOI18N
        jPanel7.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        jButton15.setBackground(new java.awt.Color(107, 116, 147));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Doctors Bag_32px.png"))); // NOI18N
        jPanel7.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jButton16.setBackground(new java.awt.Color(107, 116, 147));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ok_32px.png"))); // NOI18N
        jPanel7.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        tablaFactura1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaFactura1);

        panelFactura1.add(jScrollPane4);

        jPanel7.add(panelFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 10, 450));

        jFrame1.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 710));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 950));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 46, 68));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 820));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 820));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(12, 15, 22));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(12, 15, 22));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back_64px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 820));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visor Facturas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(109, 115, 130));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNumeroFactura.setBackground(new java.awt.Color(109, 115, 130));
        txtNumeroFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumeroFactura.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroFactura.setBorder(null);
        jPanel3.add(txtNumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtFecha.setBackground(new java.awt.Color(109, 115, 130));
        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setBorder(null);
        jPanel3.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 230, 20));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 220, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 220, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 310, 80));

        jPanel4.setBackground(new java.awt.Color(109, 115, 130));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Move by Trolley_52px.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Proveedor:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ruc: ");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ciudad:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Direccion:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 470, 10));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 190, -1));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 220, -1));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 470, -1));

        txtProveedor.setBackground(new java.awt.Color(109, 115, 130));
        txtProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtProveedor.setToolTipText("");
        txtProveedor.setBorder(null);
        txtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorActionPerformed(evt);
            }
        });
        jPanel4.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 470, 20));

        txtRuc.setBackground(new java.awt.Color(109, 115, 130));
        txtRuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRuc.setForeground(new java.awt.Color(255, 255, 255));
        txtRuc.setBorder(null);
        jPanel4.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, 20));

        txtCiudad.setBackground(new java.awt.Color(109, 115, 130));
        txtCiudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtCiudad.setBorder(null);
        jPanel4.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 220, 20));

        txtDireccion.setBackground(new java.awt.Color(109, 115, 130));
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(null);
        jPanel4.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 470, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 730, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 730, 130));

        jPanel5.setBackground(new java.awt.Color(109, 115, 130));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gender Neutral User_52px_4.png"))); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nombre:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ruc-CI:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 470, -1));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 470, 10));

        txtNombreCliente.setBackground(new java.awt.Color(109, 115, 130));
        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setBorder(null);
        jPanel5.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 470, 20));

        txtCedula.setBackground(new java.awt.Color(109, 115, 130));
        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setBorder(null);
        jPanel5.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 470, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 730, 80));

        jPanel6.setBackground(new java.awt.Color(26, 29, 40));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 115, 130));
        jLabel2.setText("Total sin IVA: ");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(109, 115, 130));
        jLabel3.setText("Total Factura:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        txtTotalSinIva.setBackground(new java.awt.Color(26, 29, 40));
        txtTotalSinIva.setForeground(new java.awt.Color(109, 115, 130));
        txtTotalSinIva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel6.add(txtTotalSinIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, 20));

        jLabel4.setBackground(new java.awt.Color(109, 115, 130));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(109, 115, 130));
        jLabel4.setText("IVA:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        txtIva.setBackground(new java.awt.Color(26, 29, 40));
        txtIva.setForeground(new java.awt.Color(109, 115, 130));
        txtIva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel6.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 80, 20));

        txtTotalFactura.setBackground(new java.awt.Color(26, 29, 40));
        txtTotalFactura.setForeground(new java.awt.Color(109, 115, 130));
        txtTotalFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel6.add(txtTotalFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 800, 40));

        btnExportarExcel.setBackground(new java.awt.Color(36, 46, 68));
        btnExportarExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExportarExcel.setForeground(new java.awt.Color(204, 204, 204));
        btnExportarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Microsoft Excel_32px_4.png"))); // NOI18N
        btnExportarExcel.setText("Exportar");
        btnExportarExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportarExcelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportarExcelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportarExcelMouseExited(evt);
            }
        });
        jPanel1.add(btnExportarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 130, 40));

        btnExportarPDF.setBackground(new java.awt.Color(36, 46, 68));
        btnExportarPDF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExportarPDF.setForeground(new java.awt.Color(204, 204, 204));
        btnExportarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PDF 2_32px.png"))); // NOI18N
        btnExportarPDF.setText("Exportar");
        btnExportarPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportarPDFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportarPDFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportarPDFMouseExited(evt);
            }
        });
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, -1, -1));

        btnSalir.setBackground(new java.awt.Color(36, 46, 68));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancel_32px.png"))); // NOI18N
        btnSalir.setText(" Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 120, -1));

        lblOtros.setBackground(new java.awt.Color(36, 46, 68));
        lblOtros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOtros.setForeground(new java.awt.Color(255, 255, 255));
        lblOtros.setText("$ 0.00");
        jPanel1.add(lblOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, -1, -1));

        lblAlimentacion.setBackground(new java.awt.Color(36, 46, 68));
        lblAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        lblAlimentacion.setText("$ 0.00");
        jPanel1.add(lblAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, -1));

        lblVestimenta.setBackground(new java.awt.Color(36, 46, 68));
        lblVestimenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVestimenta.setForeground(new java.awt.Color(255, 255, 255));
        lblVestimenta.setText("$ 0.00");
        jPanel1.add(lblVestimenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        lblSalud.setBackground(new java.awt.Color(36, 46, 68));
        lblSalud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSalud.setForeground(new java.awt.Color(255, 255, 255));
        lblSalud.setText("$ 0.00");
        jPanel1.add(lblSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        lblEducacion.setBackground(new java.awt.Color(36, 46, 68));
        lblEducacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEducacion.setForeground(new java.awt.Color(255, 255, 255));
        lblEducacion.setText("$ 0.00");
        jPanel1.add(lblEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));

        lblVivienda.setBackground(new java.awt.Color(36, 46, 68));
        lblVivienda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVivienda.setForeground(new java.awt.Color(255, 255, 255));
        lblVivienda.setText("$ 0.00");
        jPanel1.add(lblVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, -1));

        jButton5.setBackground(new java.awt.Color(107, 116, 147));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Restaurant_32px.png"))); // NOI18N
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jButton6.setBackground(new java.awt.Color(107, 116, 147));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clothes_32px.png"))); // NOI18N
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jButton7.setBackground(new java.awt.Color(107, 116, 147));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Literature_32px.png"))); // NOI18N
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        jButton8.setBackground(new java.awt.Color(107, 116, 147));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home_32px.png"))); // NOI18N
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        jButton9.setBackground(new java.awt.Color(107, 116, 147));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Doctors Bag_32px.png"))); // NOI18N
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jButton10.setBackground(new java.awt.Color(107, 116, 147));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ok_32px.png"))); // NOI18N
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaFactura);

        panelFactura.add(jScrollPane2);

        jPanel1.add(panelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 10, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPDFActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setForeground(Color.white);
        btnSalir.setBackground(new Color(89, 199, 198));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setForeground(new Color(204,204,204));
        btnSalir.setBackground(new Color(36, 46, 68));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnExportarPDFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarPDFMouseExited
        // TODO add your handling code here:
        btnExportarPDF.setForeground(new Color(204,204,204));
        btnExportarPDF.setBackground(new Color(36, 46, 68));
    }//GEN-LAST:event_btnExportarPDFMouseExited

    private void btnExportarPDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarPDFMouseEntered
        // TODO add your handling code here:
        btnExportarPDF.setForeground(Color.white);
        btnExportarPDF.setBackground(new Color(89, 199, 198));
    }//GEN-LAST:event_btnExportarPDFMouseEntered

    private void btnExportarExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarExcelMouseEntered
        // TODO add your handling code here:
        btnExportarExcel.setForeground(Color.white);
        btnExportarExcel.setBackground(new Color(89, 199, 198));
    }//GEN-LAST:event_btnExportarExcelMouseEntered

    private void btnExportarExcelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarExcelMouseExited
        // TODO add your handling code here:
        btnExportarExcel.setForeground(new Color(204,204,204));
        btnExportarExcel.setBackground(new Color(36, 46, 68));
    }//GEN-LAST:event_btnExportarExcelMouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //String direccionBase="src\\ArchivosLecturaAuxiliar";
        //direccionBase+="\\\\Bdd.s3db";
        //Reportes reportes=new Reportes(direccionBase);
        this.dispose();
        //reportes.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnExportarExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarExcelMouseClicked
        // TODO add your handling code here:
        //JTable jTableFactura = new JTable();
        DefaultTableModel modeloF = (DefaultTableModel) tablaFactura.getModel();//new DefaultTableModel(); 
        DefaultTableModel origen = (DefaultTableModel) jTable1.getModel();
        Object [] fila = new Object[5];
        tablaFactura.setModel(modeloF);
        //jTable1.setModel(origen);
        
        modeloF.addColumn("");
        modeloF.addColumn("");
        modeloF.addColumn("");
        modeloF.addColumn("");
        modeloF.addColumn("");
        
        fila[0]= "No";
        fila[1]= txtNumeroFactura.getText();
        fila[2]="";
        fila[3]="Fecha";
        fila[4]=txtFecha.getText(); 
        modeloF.addRow(fila);
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);

        fila[0]= "Proveedor:";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "Nombre";
        fila[1]= txtProveedor.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        
        fila[0]= "Ruc";
        fila[1]= txtRuc.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "Direccion";
        fila[1]= txtDireccion.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]= "Cliente";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]= "Nombre";
        fila[1]= txtNombreCliente.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "Ruc-CI";
        fila[1]= txtCedula.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);

        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Productos";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        for(int i=0;i<origen.getRowCount();i++)
        {
            for(int j=0;j<5;j++)
            {
                fila[j]= jTable1.getValueAt(i, j);
            }    
            modeloF.addRow(fila);
        }
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Alimentacion";
        fila[1]="Vestimenta";
        fila[2]="Salud";
        fila[3]="Educacion";
        fila[4]="Vivienda";
        modeloF.addRow(fila);

        fila[0]=lblAlimentacion.getText();
        fila[1]=lblVestimenta.getText();
        fila[2]=lblSalud.getText();
        fila[3]=lblEducacion.getText();
        fila[4]=lblVivienda.getText();
        modeloF.addRow(fila);

        fila[0]="Otros";
        fila[1]=lblOtros.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Total sin Iva";
        fila[1]=txtTotalSinIva.getText();
        fila[2]="IVA";
        fila[3]=txtIva.getText();
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Total Factura";
        fila[1]=txtTotalFactura.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);


        if (this.tablaFactura.getRowCount()==0) 
        {
            JOptionPane.showMessageDialog (null, "No hay datos en la tabla para exportar.","BCO",
            JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        JFileChooser chooser=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("Archivos de excel","xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar archivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION)
        {
            List<JTable> tb=new ArrayList<>();
            List<String>nom=new ArrayList<>();
            tb.add(tablaFactura);
            nom.add("Detalle de Gastos");
            String file=chooser.getSelectedFile().toString().concat(".xls");
            try 
            {    
                GeneradorExcel.Exporter e=new Exporter(new File(file),tb, nom);
                if (e.export()) 
                {
                    JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel.","BCO",
                    JOptionPane.INFORMATION_MESSAGE);
                }
            } 
            catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(null,"Hubo un error"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnExportarExcelMouseClicked

    private void btnExportarPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarPDFMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modeloF = (DefaultTableModel) tablaFactura.getModel();//new DefaultTableModel(); 
        DefaultTableModel origen = (DefaultTableModel) jTable1.getModel();
        Object [] fila = new Object[5];
        tablaFactura.setModel(modeloF);
        //jTable1.setModel(origen);
        
        modeloF.addColumn("");
        modeloF.addColumn("");
        modeloF.addColumn("");
        modeloF.addColumn("");
        modeloF.addColumn("");
        
        fila[0]= "No";
        fila[1]= txtNumeroFactura.getText();
        fila[2]="";
        fila[3]="Fecha";
        fila[4]=txtFecha.getText(); 
        modeloF.addRow(fila);
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);

        fila[0]= "Proveedor:";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "Nombre";
        fila[1]= txtProveedor.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        
        fila[0]= "Ruc";
        fila[1]= txtRuc.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "Direccion";
        fila[1]= txtDireccion.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]= "Cliente";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]= "Nombre";
        fila[1]= txtNombreCliente.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);
        
        fila[0]= "Ruc-CI";
        fila[1]= txtCedula.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";        
        modeloF.addRow(fila);

        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Productos";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        for(int i=0;i<origen.getRowCount();i++)
        {
            for(int j=0;j<5;j++)
            {
                fila[j]= jTable1.getValueAt(i, j);
            }    
            modeloF.addRow(fila);
        }
        
        fila[0]= "";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Alimentacion";
        fila[1]="Vestimenta";
        fila[2]="Salud";
        fila[3]="Educacion";
        fila[4]="Vivienda";
        modeloF.addRow(fila);

        fila[0]=lblAlimentacion.getText();
        fila[1]=lblVestimenta.getText();
        fila[2]=lblSalud.getText();
        fila[3]=lblEducacion.getText();
        fila[4]=lblVivienda.getText();
        modeloF.addRow(fila);

        fila[0]="Otros";
        fila[1]=lblOtros.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="";
        fila[1]="";
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Total sin Iva";
        fila[1]=txtTotalSinIva.getText();
        fila[2]="IVA";
        fila[3]=txtIva.getText();
        fila[4]="";
        modeloF.addRow(fila);
        
        fila[0]="Total Factura";
        fila[1]=txtTotalFactura.getText();
        fila[2]="";
        fila[3]="";
        fila[4]="";
        modeloF.addRow(fila);

        //System.out.println("num column:");
        if (this.tablaFactura.getRowCount()==0) {
        JOptionPane.showMessageDialog (null, "No hay datos en la tabla para exportar.","BCO",
        JOptionPane.INFORMATION_MESSAGE);
        //this.cmbConsorcio.grabFocus();
        return;
        }
        JFileChooser chooser=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("Archivos pdf","pdf");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar archivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        //ExporterPDF exportar = new ExporterPDF(jTableReportes, new File(file), "Reporteeeeee");
        if (chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            List<JTable> tb=new ArrayList<>();
            List<String>nom=new ArrayList<>();
            tb.add(tablaFactura);
            nom.add("Detalle de Gastos");
            String file=chooser.getSelectedFile().toString().concat(".pdf");
            System.out.println("El valor de file es:"+file);
            try 
            {
                //GeneradorPDF.ExporterPDF e = new ExporterPDF(new File(file),tb, nom);
                GeneradorPDF.ExporterPDF e = new ExporterPDF(tablaFactura, new File(file), "Reporteeeeee", file);
                //GeneradorExcel.Exporter e=new Exporter(new File(file),tb, nom);
                if (e.exportarPDF()) 
                {
                    JOptionPane.showMessageDialog(null, "Los datos fueron exportados a pdf.","BCO",
                        JOptionPane.INFORMATION_MESSAGE);

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Hubo un error"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnExportarPDFMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedor1ActionPerformed

    private void btnExportarExcel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarExcel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarExcel1MouseClicked

    private void btnExportarExcel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarExcel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarExcel1MouseEntered

    private void btnExportarExcel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarExcel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarExcel1MouseExited

    private void btnExportarPDF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarPDF1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPDF1MouseClicked

    private void btnExportarPDF1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarPDF1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPDF1MouseEntered

    private void btnExportarPDF1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarPDF1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPDF1MouseExited

    private void btnExportarPDF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarPDF1ActionPerformed

    private void btnSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MouseClicked

    private void btnSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MouseEntered

    private void btnSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MouseExited

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseReleased
                          


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresentarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnExportarExcel1;
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JButton btnExportarPDF1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAlimentacion;
    private javax.swing.JLabel lblAlimentacion1;
    private javax.swing.JLabel lblEducacion;
    private javax.swing.JLabel lblEducacion1;
    private javax.swing.JLabel lblOtros;
    private javax.swing.JLabel lblOtros1;
    private javax.swing.JLabel lblSalud;
    private javax.swing.JLabel lblSalud1;
    private javax.swing.JLabel lblVestimenta;
    private javax.swing.JLabel lblVestimenta1;
    private javax.swing.JLabel lblVivienda;
    private javax.swing.JLabel lblVivienda1;
    private javax.swing.JPanel panelFactura;
    private javax.swing.JPanel panelFactura1;
    private javax.swing.JTable tablaFactura;
    private javax.swing.JTable tablaFactura1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedula1;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCiudad1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFecha1;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtIva1;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreCliente1;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtNumeroFactura1;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtProveedor1;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtRuc1;
    private javax.swing.JTextField txtTotalFactura;
    private javax.swing.JTextField txtTotalFactura1;
    private javax.swing.JTextField txtTotalSinIva;
    private javax.swing.JTextField txtTotalSinIva1;
    // End of variables declaration//GEN-END:variables
}
